PROJECT = hello_world

all:
	quartus_sh --flow compile $(PROJECT)

clean:
	rm -rf c5_pin_model_dump.txt
	rm -rf db/
	rm -rf hello_world_assignment_defaults.qdf
	rm -rf hello_world.asm.rpt
	rm -rf hello_world.done
	rm -rf hello_world.fit.rpt
	rm -rf hello_world.fit.smsg
	rm -rf hello_world.fit.summary
	rm -rf hello_world.flow.rpt
	rm -rf hello_world.jdi
	rm -rf hello_world.map.rpt
	rm -rf hello_world.map.summary
	rm -rf hello_world.pin
	rm -rf hello_world.qpf
	rm -rf hello_world.sld
	rm -rf hello_world.sof
	rm -rf hello_world.sta.rpt
	rm -rf hello_world.sta.summary
	rm -rf incremental_db/

