// mem_0.v

// Generated using ACDS version 20.2 50

`timescale 1 ps / 1 ps
module mem_0 (
		input  wire [31:0] data,    //    data.datain
		output wire [31:0] q,       //       q.dataout
		input  wire [7:0]  address, // address.address
		input  wire        wren,    //    wren.wren
		input  wire        clock    //   clock.clk
	);

	mem_0_ram_1port_2010_jwk6vpy ram_1port_0 (
		.data    (data),    //   input,  width = 32,    data.datain
		.q       (q),       //  output,  width = 32,       q.dataout
		.address (address), //   input,   width = 8, address.address
		.wren    (wren),    //   input,   width = 1,    wren.wren
		.clock   (clock)    //   input,   width = 1,   clock.clk
	);

endmodule
